---
title: "hw2"
author: "cyberatlas"
date: "February 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1)

```{r}
library(ggplot2)
#Loads the data
mpg
#Shows the data
str(mpg)

#1
#Save the mpg table as a dataframe
mpgDF <- data.frame(mpg)
head(mpgDF)

#Sorts the mpg data frame by the hwy value
#Because it sorts in ascending order, we reversed that with a -
sortedList<- mpgDF[order(-mpg$hwy),]
#Makes a data frame with the values at the top of sorted list
top3 <- head(sortedList, 3)
#print the dataframe
print(top3)
```

2)
```{r}
#The reason you need a comma is because it does not know if you are specifying rows or columns
#After the comma, specifies what other columns to return. Not specified = all of them
noRepeats <- mpgDF[mpgDF$class == 'compact',]
print(noRepeats)
#Removes duplicate compact models
noDupes <- unique(noRepeats$model)
#class(noDupes)
#Makes noDupes a data frame
noDupes <- data.frame(noDupes)
str(noDupes)
print(noDupes)
#class(noDupes)
#Variable to store the number of different compact car models 
numCompact <- length(noDupes)
#Prints the number of compact cars on the list
print(numCompact)

```

```{r}
#Grab all of the hwy values by selecting the column in the dataframe
hwy <- data.frame(mpgDF$hwy)
hwy
#Grab all of the cty values by selecting teh column in the dataframe
cty <- data.frame(mpgDF$cty)
cty

#More ggplot stuff 
#http://www.sthda.com/english/wiki/ggplot2-title-main-axis-and-legend-titles
#Uses ggplot2 to make a scatterplot with 
ggplot(mpgDF, aes(x=hwy, y=cty)) +
  geom_point(shape=1) + 
  geom_smooth(method=lm,
              se=FALSE) +
  ggtitle("Hwy by cty")
```


As the hwy increases, the cty is increases more slowly than hwy

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
